---
title: "468_cbe2"
author: "Haley Jiang"
date: "2022-11-19"
output: pdf_document
---

```{r setup, message = FALSE, error=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmu.textstat)
library(tidyverse)
library(quanteda)
library(nnet)
library(quanteda.textstats)
```

## Load data

```{r read_files, echo=FALSE}
nolan_files_list <- list.files("data", full.names = T)

nolan_files_list
```

```{r}
nolan_meta <- tibble(doc_id = nolan_files_list,
                     year = c(2005,2012, 2008, 2017, 1998, 2010,
                              2002, 2014, 2000, 2006, 2020),
                     movie = c("batman_begins", "dark_knight_rises", "dark_knight",
                               "dunkirk", "following", "incepetion", "insomnia",
                               "interstallar", "memento", "prestige", "tenet"))
  
nolan_corpus <- nolan_files_list %>%
  readtext::readtext() %>%
  mutate(text = preprocess_text(text,
                                contractions = TRUE,
                                hypens = TRUE,
                                punctuation = TRUE,
                                lower_case = TRUE,
                                accent_replace = TRUE,
                                remove_numbers = TRUE)) %>%  
  corpus()

docvars(nolan_corpus) <- nolan_meta
```


## Parse data


