---
title: "text_analysis_CBE2"
author: "Handi Yang"
date: "11/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cmu.textstat)
library(readtext)
library(tidyverse)
library(quanteda)
library(quanteda.textstats)
library(ggraph)
library(corpus)
library(syuzhet)
library(udpipe)
library(pseudobibeR)
library(readr)
library(nFactors)
library(future.apply)
library(wordcloud)
library(tidytext)
library(tm)
```

```{r}
# load data
# setwd("/Users/yanghandi/Desktop")
script_df <- readtext("./data") %>%
   mutate(text = preprocess_text(text,
                                 contractions = TRUE,
                                 hypens = TRUE,
                                 punctuation = TRUE,
                                 # lower_case = TRUE,
                                 accent_replace = TRUE,
                                 remove_numbers = TRUE))

script <- corpus(script_df)

corpus <- script_df %>%
  mutate(text_type = str_extract(doc_id, "^[a-z]+")) %>%
  dplyr::select(doc_id, text)


corpus_split <- split(corpus, seq(1, nrow(corpus), by = 10))

library(future.apply)


ncores <- 4L
plan(multisession, workers = ncores)

annotate_splits <- function(corpus_text) {
  ud_model <- udpipe_load_model("english-ewt-ud-2.5-191206.udpipe")
  x <- data.table::as.data.table(udpipe_annotate(ud_model, x = corpus_text$text,
                                                 doc_id = corpus_text$doc_id))
  return(x)
}

annotation <- future_lapply(corpus_split, annotate_splits, future.seed = T)

annotation <- data.table::rbindlist(annotation)

anno_edit <- annotation %>%
  dplyr::select(doc_id, sentence_id, token_id, token, lemma, upos, xpos, head_token_id, dep_rel) %>%
  rename(pos = upos, tag = xpos)

anno_edit <- structure(anno_edit, class = c("spacyr_parsed", "data.frame"))


tkns <- as.tokens(anno_edit, include_pos = "pos", concatenator = "_")

doc_categories <- names(tkns) %>%
  data.frame(text_type = .) %>%
  mutate(text_type = str_extract(text_type, "^[a-z]+"))

docvars(tkns) <- doc_categories

script_dfm <- dfm(tkns)

script_dfm <- tkns %>%
  tokens_select("^.*[a-zA-Z0-9]+.*_propn", selection = "remove", valuetype = "regex", case_insensitive = T) %>%
  dfm()

script_tokens <- tokens(script)

```

```{r}
ud_model <- udpipe_load_model("english-ewt-ud-2.5-191206.udpipe")

annotation <- udpipe(script_df, "english")

# parse data
script_prsd <- udpipe_annotate(ud_model, x = script_df$text, doc_id = script_df$doc_id)
# convert to dataframe
script_prsd <- data.frame(script_prsd, stringsAsFactors = F)
# biber
script_biber <- biber_udpipe(script_prsd)
```
```{r}
script_tokens %>%  tokens_select()
```



```{r Assign meta data}
# summary of dataset
script_name <- str_extract(script_df$doc_id, "^[a-z]+")
release_year <- c(2005, 2008, 2012, 2010, 2020, 2014, 1998, 2002, 2000, 2006, 2017)
docvars(script, field = "text_type") <- script_name
docvars(script, field = "year") <- release_year
knitr::kable(script %>% summary(), caption = "Summary of Norlan film corpus.")
```

```{r}
# frequency

freq_df <- textstat_frequency(script_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(freq_df[1:20,], caption = "The 20 most frequent tokens in the script corpus.")
# war movie
war_dfm <- dfm_subset(script_dfm, text_type == "war")
war_freq_df <- textstat_frequency(war_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(war_freq_df[1:20,], caption = "The 20 most frequent tokens in the war movie corpus.")
# scientific
scientific_dfm <- dfm_subset(script_dfm, text_type == "scientific")
scie_freq_df <- textstat_frequency(scientific_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(scie_freq_df[1:20,], caption = "The 20 most frequent tokens in the scientific movie corpus.")
# action
action_dfm <- dfm_subset(script_dfm, text_type == "action")
act_freq_df <- textstat_frequency(action_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(act_freq_df[1:20,], caption = "The 20 most frequent tokens in the actio n movie corpus.")
# thriller
thriller_dfm <- dfm_subset(script_dfm, text_type == "thriller")
thr_freq_df <- textstat_frequency(thriller_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(thr_freq_df[1:20,], caption = "The 20 most frequent tokens in the thriller movie corpus.")
```

```{r}
# wayne collocation - does not necessary to include
wayne_collocations <- collocates_by_MI(script_tokens, "wayne")
mc <- wayne_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(wayne_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)
```

```{r}
# keyness - not necessary to include
corpus_comp <- ntoken(script_dfm) %>% 
  data.frame(Tokens = .) %>%
  rownames_to_column("Text_Type") %>%
  mutate(Text_Type = str_extract(Text_Type, "^[a-z]+")) %>%
  group_by(Text_Type) %>%
  dplyr::summarize(Texts = n(),
    Tokens = sum(Tokens)) %>%
  mutate(Text_Type = c("war", "scientific", "action", "thriler")) %>%
  rename("Text-Type" = Text_Type) %>%
  janitor::adorn_totals()
```

```{r}
# scientific
scientific_kw <- textstat_keyness(script_dfm, docvars(script_dfm, "text_type") == "scientific", measure = "lr")
kableExtra::kbl(head(scientific_kw), caption = "Tokens with the highest keyness values in the scientific text-type when compared to the rest of the sample corpus.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```
```{r}
# thriller
thriller_dfm <- dfm_subset(script_dfm, text_type == "thriller")
thriller_kw <- textstat_keyness(script_dfm, docvars(script_dfm, "text_type") == "thriller", measure = "lr")
kableExtra::kbl(head(thriller_kw), caption = "Tokens with the highest keyness values in the thriller text-type when compared to the rest of the sample corpus.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```
```{r}
# war
war_dfm <- dfm_subset(script_dfm, text_type == "war")
war_kw <- textstat_keyness(script_dfm, docvars(script_dfm, "text_type") == "war", measure = "lr")
kableExtra::kbl(head(war_kw), caption = "Tokens with the highest keyness values in the war text-type when compared to the rest of the sample corpus.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```

```{r}

```

collocations
```{r}
# collocation protagonist
```

```{r}
science_sus <- keyness_table(scientific_dfm, suspense_dfm)
kableExtra::kbl(head(science_sus), caption = "Tokens with the highest keyness values in the scientific movie when compared to other genre.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```
```{r}
sus_science <- keyness_table(suspense_dfm, scientific_dfm)
kableExtra::kbl(head(sus_science), caption = "Tokens with the highest keyness values in the suspense movie when compared to the scientific movie.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()

```
```{r}
con_collocations <- collocates_by_MI(script_tokens, "continuous")
mc <- con_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(con_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)
```

```{r}
# select specific word from each text

```



