---
title: "CBE2_haley"
author: "Handi Yang"
date: "12/10/2022"
output: html_document
---

```{r}
library(tidyverse)
library(cmu.textstat)
library(readtext)
library(tidyverse)
library(quanteda)
library(quanteda.textstats)
library(ggraph)
library(corpus)
library(syuzhet)
library(udpipe)
# library(pseudobibeR)
library(readr)
library(nFactors)
library(future.apply)
library(wordcloud)
library(tidytext)
library(tm)
```

```{r}
# load data
# setwd("/Users/yanghandi/Desktop")
script_df <- readtext("./468_final_project/data") %>%
   mutate(text = preprocess_text(text,
                                 contractions = TRUE,
                                 hypens = TRUE,
                                 punctuation = TRUE,
                                 # lower_case = TRUE,
                                 accent_replace = TRUE,
                                 remove_numbers = TRUE))

script <- corpus(script_df)

corpus <- script_df %>%
  mutate(genre = str_extract(doc_id, "^[a-z]+")) %>%
  dplyr::select(doc_id, text)

# assign meta data
movie_genre <- str_extract(script_df$doc_id, "^[a-z]+")
docvars(script, field = "genre") <- movie_genre
release_year <- str_extract(script_df$doc_id,"(\\d+)(?!.*\\d)")
# release_year <- c(2005, 2008, 2012, 2010, 2020, 2014, 1998, 2002, 2000, 2006, 2017)
docvars(script, field = "year") <- release_year
knitr::kable(script %>% summary() %>% base::subset(select=-c(Types, Sentences)), caption = "Summary of Norlan film corpus.")
corpus_split <- split(corpus, seq(1, nrow(corpus), by = 10))
```

```{r}
# remove proper noun from dataset
library(future.apply)
ncores <- 4L
plan(multisession, workers = ncores)
annotate_splits <- function(corpus_text) {
  ud_model <- udpipe_load_model("english-ewt-ud-2.5-191206.udpipe")
  x <- data.table::as.data.table(udpipe_annotate(ud_model, x = corpus_text$text,
                                                 doc_id = corpus_text$doc_id))
  return(x)
}
annotation <- future_lapply(corpus_split, annotate_splits, future.seed = T)
annotation <- data.table::rbindlist(annotation)
anno_edit <- annotation %>%
  dplyr::select(doc_id, sentence_id, token_id, token, lemma, upos, xpos, head_token_id, dep_rel) %>%
  rename(pos = upos, tag = xpos)
anno_edit <- structure(anno_edit, class = c("spacyr_parsed", "data.frame"))
tkns <- as.tokens(anno_edit, include_pos = "pos", concatenator = "_")
doc_categories <- names(tkns) %>%
  data.frame(genre = .) %>%
  mutate(genre = str_extract(genre, "^[a-z]+"))
docvars(tkns) <- doc_categories
script_dfm <- dfm(tkns)
script_dfm <- tkns %>%
  tokens_select("^.*[a-zA-Z0-9]+.*_propn", selection = "remove", valuetype = "regex", case_insensitive = T) %>%
  dfm()
# get token 
script_tokens <- tokens(script)
```

```{r}
# # biber annotation
# ud_model <- udpipe_load_model("english-ewt-ud-2.5-191206.udpipe")
# annotation <- udpipe(script_df, "english")
# # parse data
# script_prsd <- udpipe_annotate(ud_model, x = script_df$text, doc_id = script_df$doc_id)
# # convert to dataframe
# script_prsd <- data.frame(script_prsd, stringsAsFactors = F)
# # biber
# script_biber <- biber_udpipe(script_prsd)
```



```{r}
# frequency
freq_df <- textstat_frequency(script_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(freq_df[1:20,], caption = "The 20 most frequent tokens in the script corpus.")
# war movie
war_dfm <- dfm_subset(script_dfm, genre == "war")
war_freq_df <- textstat_frequency(war_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(war_freq_df[1:20,], caption = "The 20 most frequent tokens in the war movie corpus.")
# scientific
scientific_dfm <- dfm_subset(script_dfm, genre == "scientific")
scie_freq_df <- textstat_frequency(scientific_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(scie_freq_df[1:20,], caption = "The 20 most frequent tokens in the scientific movie corpus.")
# action
action_dfm <- dfm_subset(script_dfm, genre == "action")
act_freq_df <- textstat_frequency(action_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(act_freq_df[1:20,], caption = "The 20 most frequent tokens in the actio n movie corpus.")
# thriller
thriller_dfm <- dfm_subset(script_dfm, genre == "thriller")
thr_freq_df <- textstat_frequency(thriller_dfm) %>%
  data.frame(stringsAsFactors = F)
knitr::kable(thr_freq_df[1:20,], caption = "The 20 most frequent tokens in the thriller movie corpus.")
```

```{r}
# the collocation - does not necessary to include
the_collocations <- collocates_by_MI(script_tokens, "the")
mc <- the_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(the_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)
```

```{r collocation in war}
# action corpus select
script_df <- script_df %>%
  mutate(genre = str_extract(doc_id, "^[a-z]+"))
action_df <- subset(script_df, genre == "action")
action_tokens <- action_df %>%
  mutate(text = preprocess_text(text)) %>%
  corpus() %>%
  tokens(what="fastestword", remove_numbers=TRUE)

# get collocation far action corpus
the_collocations <- collocates_by_MI(action_tokens, "the")
mc <- the_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(the_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)

```

```{r science collocation for the}
# war corpus select
war_df <- subset(script_df, genre == "war")
war_tokens <- war_df %>%
  mutate(text = preprocess_text(text)) %>%
  corpus() %>%
  tokens(what="fastestword", remove_numbers=TRUE)

# get collocation far war corpus
the_collocations <- collocates_by_MI(war_tokens, "the")
mc <- the_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(the_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)
```

```{r thriler collocation}
# thriller corpus select
thriller_df <- subset(script_df, genre == "thriller")
thriller_tokens <- thriller_df %>%
  mutate(text = preprocess_text(text)) %>%
  corpus() %>%
  tokens(what="fastestword", remove_numbers=TRUE)

# get collocation far war corpus
the_collocations <- collocates_by_MI(thriller_tokens, "the")
mc <- the_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(the_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)
```

```{r science}
science_df <- subset(script_df, genre == "scientific")
science_tokens <- science_df %>%
  mutate(text = preprocess_text(text)) %>%
  corpus() %>%
  tokens(what="fastestword", remove_numbers=TRUE)

# get collocation far science corpus
the_collocations <- collocates_by_MI(science_tokens, "the")
mc <- the_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(the_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)
```

```{r}
# keyness - not necessary to include
corpus_comp <- ntoken(script_dfm) %>% 
  data.frame(Tokens = .) %>%
  rownames_to_column("genre") %>%
  mutate(genre = str_extract(genre, "^[a-z]+")) %>%
  group_by(genre) %>%
  dplyr::summarize(Texts = n(),
    Tokens = sum(Tokens)) %>%
  mutate(genre = c("war", "scientific", "action", "thriler")) %>%
  rename("Text-Type" = genre) %>%
  janitor::adorn_totals()
```

```{r}
# scientific
scientific_kw <- textstat_keyness(script_dfm, docvars(script_dfm, "genre") == "scientific", measure = "lr")
kableExtra::kbl(head(scientific_kw), caption = "Tokens with the highest keyness values in the scientific text-type when compared to the rest of the sample corpus.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```

```{r}
# thriller
thriller_dfm <- dfm_subset(script_dfm, genre == "thriller")
thriller_kw <- textstat_keyness(script_dfm, docvars(script_dfm, "genre") == "thriller", measure = "lr")
kableExtra::kbl(head(thriller_kw), caption = "Tokens with the highest keyness values in the thriller text-type when compared to the rest of the sample corpus.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```

```{r}
# war
war_dfm <- dfm_subset(script_dfm, genre == "war")
war_kw <- textstat_keyness(script_dfm, docvars(script_dfm, "genre") == "war", measure = "lr")
kableExtra::kbl(head(war_kw), caption = "Tokens with the highest keyness values in the war text-type when compared to the rest of the sample corpus.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```

```{r}
```

collocations
```{r}
# collocation protagonist
```

```{r}
science_sus <- keyness_table(scientific_dfm, suspense_dfm)
kableExtra::kbl(head(science_sus), caption = "Tokens with the highest keyness values in the scientific movie when compared to other genre.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```

```{r}
sus_science <- keyness_table(suspense_dfm, scientific_dfm)
kableExtra::kbl(head(sus_science), caption = "Tokens with the highest keyness values in the suspense movie when compared to the scientific movie.", booktabs = T, linesep = "", digits = 2) %>%
  kableExtra::kable_styling(latex_options = "HOLD_position") %>%
  kableExtra::kable_classic()
```

```{r}
con_collocations <- collocates_by_MI(script_tokens, "continuous")
mc <- con_collocations %>% filter(col_freq >= 5 & MI_1 >= 5)
knitr::kable(head(con_collocations), digits = 3)
knitr::kable(head(mc), digits = 3)
```


```{r DocuScope}
ds_counts <- script_tokens %>%
  tokens_lookup(dictionary = quanteda.extras::ds_dict, levels = 1, valuetype = "fixed") %>%
  dfm() %>%
  convert(to = "data.frame")

tot_counts <- quanteda::ntoken(script_tokens) %>%
  data.frame(tot_counts = .) %>%
  tibble::rownames_to_column("doc_id") %>%
  dplyr::as_tibble()

ds_counts <- dplyr::full_join(ds_counts, tot_counts, by = "doc_id")

ds_counts <- ds_counts %>%
  dplyr::mutate_if(is.numeric, list(~./tot_counts), na.rm = TRUE) %>%
  dplyr::mutate_if(is.numeric, list(~.*100), na.rm = TRUE) %>%
  dplyr::select(-tot_counts)

pca <- prcomp(ds_counts[-1], center = TRUE, scale. = TRUE)
summary(pca)


library(factoextra)
fviz_eig(pca, addlabels = TRUE, ncp = 11) +
  geom_hline(yintercept = 100 * (1 / ncol(pca$x)),
             linetype = "dashed", color = "darkred") +
  labs(title = "The first and second principal components explain
       more than 50% of the variances")

pc_matrix <- pca$x

# movie_genre <- str_extract(script_df$doc_id, "^[a-z]+")
# docvars(script, field = "genre") <- movie_genre
# release_year <- str_extract(script_df$doc_id,"(\\d+)(?!.*\\d)")
# # release_year <- c(2005, 2008, 2012, 2010, 2020, 2014, 1998, 2002, 2000, 2006, 2017)
# docvars(script, field = "year") <- release_year

quant <- ds_counts %>%
  mutate(pc1 =  pc_matrix[,1],
         pc2 =  pc_matrix[,2],
         doc_id = ds_counts$doc_id,
         genre = movie_genre,
         release_year = release_year)

quant %>%
  ggplot(aes(x = pc1, y = pc2, color = genre)) +
  geom_point(alpha = 0.5) +
  labs(x = "The first principal component",
        y = "The second principal component",
title = "Movie genre is associated with the first principal component")

fviz_pca_biplot(pca, pointshape = 19,
                label =  "var",
                # Plot PC1 and PC2
                axes = c(1, 2),
                # Change the alpha for the observations -
                # which is represented by ind
                alpha.ind = 0.25,
                # Modify the alpha for the variables (var):
                alpha.var = 0.75,
                repel = TRUE,
                # Set the color of the points to decades variable:
                col.ind = spotify_songs$track_popularity,
                # Modify the color of the variables
                col.var = "purple")  +
  labs(title = "Playlist genre is associated with 
       the first principal component", color = "Playlist genre") +
  theme(legend.position = "bottom")

fviz_pca_biplot(pca,
                pointshape = 19,
                # geom.ind = "points",
                label =  "var",
                # Plot PC1 and PC2
                axes = c(1, 2),
                # Change the alpha for the observations -
                # which is represented by ind
                alpha.ind = 0.5,
                # Modify the alpha for the variables (var):
                alpha.var = 0.75,
                repel = TRUE,
                # Set the color of the points to decades variable:
                col.ind = (quant$genre),
                # Modify the color of the variables
                col.var = "orange") +
  labs(title = "PC1 vs PC2 by movie genres",
       x = "The first principal component", 
       y = "The second principal component",
       color = "Movie genres") +
  theme(legend.position = "bottom")

```

```{r}
rotation_df <- as.data.frame(pca$rotation) 
action_feature_df <- rotation_df[rotation_df$PC1 > 0 & rotation_df$PC2 > 0,] %>% 
  mutate(rat_pc1_pc2 = 
           rotation_df[rotation_df$PC1 > 0 & rotation_df$PC2 > 0,]$PC1/
           rotation_df[rotation_df$PC1 > 0 & rotation_df$PC2 > 0,]$PC2) %>% 
  subset(select = c(PC1, PC2, rat_pc1_pc2))
```
```{r}
action_feature_neg_df <- rotation_df[rotation_df$PC1 < 0 & rotation_df$PC2 < 0,] %>% 
  mutate(rat_pc1_pc2 = 
           rotation_df[rotation_df$PC1 < 0 & rotation_df$PC2 < 0,]$PC1/
           rotation_df[rotation_df$PC1 < 0 & rotation_df$PC2 < 0,]$PC2) %>% 
  subset(select = c(PC1, PC2, rat_pc1_pc2))
```


